version: '3'
services:
 myfinalappimg:
   build: ./warrepo
   ports:
        - "8887:8080"
            container_name: nomdelamachine
	    depends_on:
	      - db
	        db:
                 build: ./postgresql
                 ports:
                     - "5432:5432"
                      volumes:
		      dbdata:/var/lib/postgresql/data
                       container_name: db

                                 volumes:
                                  dbdata:
